### ISSUE TITLE
xml bool not working properly

### ISSUE THREAD

**Issue by sarim** [DHowett/go-plist#14] opened 2015-05-31 10:45 UTC
In xml, bool types are encoded as string. If i set go type to `bool`. It doesn't work, always returns false. But if i set go type to `string`, it returns `yes` as string. But i want it to decode to bool type. Also it seems like `plist.Unmarshal` doesn't call the struct's `UnmarshalPlist` method either. I could use a auxiliary struct to fix this inside UnmarshalPlist method.

**Comment by DHowett** [comment] 2015-05-31 18:51
Can you include an example of a plist that's failing? The test cases include `<true/>` and `<false/>`, which are the only correct encodings for booleans.

UnmarshalPlist support is not yet merged, but it is on my list of things to do!

**Comment by sarim** [comment] 2015-05-31 19:47
a part of `$ system_profiler SPUSBDataType -xml > test.plist`

```xml
<key>_name</key>
<string>StoreJet Transcend</string>
<key>bcd_device</key>
<string>80.00</string>
<key>bsd_name</key>
<string>disk3</string>
<key>bus_power</key>
<string>500</string>
<key>bus_power_used</key>
<string>100</string>
<key>detachable_drive</key>
<string>yes</string>
<key>device_speed</key>
<string>high_speed</string>
<key>location_id</key>
<string>0x1d170000 / 3</string>
<key>manufacturer</key>
<string>StoreJet Transcend</string>
<key>partition_map_type</key>
<string>master_boot_record_partition_map_type</string>
<key>product_id</key>
<string>0x5106</string>
<key>removable_media</key>
<string>yes</string>
<key>serial_num</key>
<string>S2S6J9GD103991</string>
<key>size</key>
<string>1 TB</string>
<key>size_in_bytes</key>
<integer>1000204886016</integer>
<key>smart_status</key>
<string>Not Supported</string>
<key>vendor_id</key>
<string>0x174c  (ASMedia Technology Inc.)</string>
```

See the `removable_media` entry.

**Comment by DHowett** [comment] 2015-05-31 19:57
That is in fact a string containing `yes`. In XML property lists, booleans are encoded as `<true/>` and `<false/>`.

Unfortunately, it appears as though `system_profiler` is the incorrect party here.

**Comment by sarim** [comment] 2015-05-31 20:03
Hmm. I've seen some other apple tools generate XMLs with string yes/no.
Well, will wait for `UnmarshalPlist`

**Comment by DHowett** [comment] 2017-03-06 08:48
Closing as a dupe of #13.

**Closed by DHowett** 2017-03-06 08:48 UTC
