### ISSUE TITLE
 howett.net/plist is returning a 404, which breaks all packages

### ISSUE THREAD

**Issue by ereOn** [DHowett/go-plist#43] opened 2019-07-02 20:55 UTC
Hi,

Apparently,  https://howett.net/plist returns a 404 which breaks all depending packages.

Thanks,

**Comment by DHowett** [comment] 2019-07-03 00:34
Hey @ereOn, thanks for the report. I can't reproduce this!

Would you mind sharing the output of `curl -v 'https://howett.net/plist?go-get=1'`? When I run it, I get this:

```
(Libra) / % curl -v 'https://howett.net/plist?go-get=1'
*   Trying 13.77.158.121...
* TCP_NODELAY set
* Connected to howett.net (13.77.158.121) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=howett.net
*  start date: Jun  4 14:14:17 2019 GMT
*  expire date: Sep  2 14:14:17 2019 GMT
*  subjectAltName: host "howett.net" matched cert's "howett.net"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fffd02bcd30)
> GET /plist?go-get=1 HTTP/2
> Host: howett.net
> User-Agent: curl/7.63.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200
< content-type: text/html; charset=utf-8
< content-length: 137
< date: Wed, 03 Jul 2019 00:32:42 GMT
<
<!DOCTYPE html>
<html><head>
<meta name="go-import" content="howett.net/plist git https://gitlab.howett.net/go/plist.git">
```

If you visit howett.net/plist in a browser, you're getting a different result than `go get` will get. Adding `?go-get=1` makes sure you're getting the same experience as Go.

**Comment by DHowett** [comment] 2019-09-28 22:38
(no other reports, and no repro is forthcoming; closing. let me know if it kept up.)

**Closed by DHowett** 2019-09-28 22:38 UTC
