### ISSUE TITLE
How to handle unknown types?

### ISSUE THREAD

**Issue by sapieneptus** [DHowett/go-plist#17] opened 2015-10-12 20:27 UTC
Apple's Provisioning Profile plists sometimes contain variable types. E.g., `AssociatedDomains` for an app are sometimes Arrays and sometimes Strings. So if we have an interface:

```
type Profile struct {
 AssociatedDomains []string `plist:com.apple.associated.domains`
}
```

We will get an error if we try to decode this and the AssociatedDomains are a string. 

Is there some way to handle this case?

**Comment by DHowett** [comment] 2015-10-18 05:27
There's an open pull request #13 implementing custom unmarshalling. I haven't had a chance to look over it, but I do want to get it merged in at some point. You could give it a try!

**Comment by DHowett** [comment] 2017-03-06 06:27
Duplicate of #13.

**Closed by DHowett** 2017-03-06 06:27 UTC
